# Generated by Django 5.2.8 on 2025-11-29 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Tables already exist in Supabase
    ]
